### ISSUE TITLE
TLSV1_ALERT_INTERNAL_ERROR while executing python checkpwnedemails.py -s 

### ISSUE THREAD

**Issue by robertszewczyk** [Techno-Hwizrdry/checkpwnedemails#2]
`python checkpwnedemails.py -s mymail@lavabit.com
Traceback (most recent call last):
  File "checkpwnedemails.py", line 187, in <module>
    main()
  File "checkpwnedemails.py", line 179, in main
    results.append(get_results(email_list, BREACHED, opts))
  File "checkpwnedemails.py", line 58, in get_results
    response = urllib2.urlopen(req)  # This is a json object.
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:661)>`

**Comment by Techno-Hwizrdry** [comment]
What version of python are you running?
What OS are you running checkpwnedemails.py on?
What opensll libraries are you using for your OS and python?

**Comment by robertszewczyk** [comment]
macOS Sierra. Python 2.7.13 (v2.7.13:a06454b1afa1) and OpenSSL 0.9.8zh 14 Jan 2016.

On my Linux box ti works perfectly.

**Comment by Techno-Hwizrdry** [comment]
Hey there,

It appears that you need to update the OpenSSL libraries on your mac and install python with the new OpenSSL libraries.  I just fixed this issue on a macOS El Capitan machine and here's what I did (at the command line) in order to resolve this issue.  Before you execute them, make sure you have /usr/local/bin in your $PATH.

```
brew update
brew upgrade openssl
brew link openssl --force
brew install python --with-brewed-openssl
sudo ln -s /usr/local/Cellar/python/2.7.13_1/bin/python2 /usr/local/bin/python
```

If you execute `python --version` and `python -c "import ssl; print ssl.OPENSSL_VERSION"` you should see _Python 2.7.13_ and _OpenSSL 1.0.2l  25 May 2017_ as output (respectively).

When you get a chance, feel free let me know how it this works out for you.

Cheers,
       Techno-Hwizrdry

**Comment by robertszewczyk** [comment]
Yep. Worked. Thank you.
