### ISSUE TITLE
Unable to use -o option, Please help

### ISSUE THREAD

**Issue by Mr-P-D** [Techno-Hwizrdry/checkpwnedemails#5]
Command:
python checkpwnedemails.py -a hibp-api-key.txt -s email -o tab-output.txt

Output:
Traceback (most recent call last):
  File "checkpwnedemails.py", line 239, in <module>
    main()
  File "checkpwnedemails.py", line 235, in main
    write_results_to_file(opts.output_path, results, opts)
  File "checkpwnedemails.py", line 185, in write_results_to_file
    outfile = open(filename + f, 'w', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

Can you please let me know what i am doing wrong ? i made the file with excel and added there

**Comment by Mr-P-D** [comment]
Apologies Author, i used python3  and then it worked

I Used:
python3 checkpwnedemails.py -a hibp-api-key.txt -s email -o tab-output.txt

now i feel so stupid
